version: 2
updates:
  # SECURITY UPDATES - WEEKLY
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    security-updates-only: true
    target-branch: "main"  # Or your preferred branch
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "security"
    groups:
      pip-security:
        applies-to: "security-updates"
        patterns:
          - "*"

  # REGULAR UPDATES - MONTHLY
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "04:00"
      timezone: "Asia/Taipei"
    target-branch: "main"
    security-updates-only: false
    open-pull-requests-limit: 3
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-type: "indirect"
    labels:
      - "dependencies"
    groups:
      pip-monthly:
        applies-to: "all"
        patterns:
          - "*"
