# Project information
site_name: 'My Notes' 
site_description: 'A Material Design theme for my personal notes'
site_author: 'Victor Andres Aguirre Fernandez'
site_url: ''

# Repository
repo_name: 'My_notes'
repo_url: 'https://github.com/CubeVic/My_notes'

# Copyright
copyright: 'Copyright &copy; 2019 -  Victor Aguirre'

theme:
  name: 'material'
  language: 'en'
  palette:
      primary: 'grey'
      accent: 'Indigo'
  font: 
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  logo: '/images/Logo.png'
  favicon: 'img/favicon.ico.png'
  feature:
      tabs: true

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML

# Extensions
markdown_extensions:
  - pymdownx.arithmatex
  - admonition
  - footnotes
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
      separator: "_"


# Navigation
nav:
    - Home: 'index.md'
    - Machine Leaning: 
      - Key ML Terminology: 'Key ML Terminology.md'
      - Other Key Terminology (TensorFlow): 'Other_key_Terminology.md'
      - Linear Regression: 'Linear regression.md'
    - Miscellaneous:
      - Python:
        - Data Structures: 'Data structures.md'
      - OAuth 2: 'OAuth_2.md'
      - Random: 'Random Link.md'
    - Courses:
          - Coursera:
            - AI for Everyone: 'AI_for_Everyone.md'
    - About: 'about.md'