site_name: My Notes 
repo_url: https://github.com/CubeVic/My_notes
nav:
  - Home: 'index.md'
  - Machine leaning: 
     - Key ML Terminology: 'Key ML Terminology.md'
     - Linear Regression: 'Linear regression.md'
  - Miscellaneous:
      - OAuth 2: OAuth_2.md
  - About: 'about.md'

theme:
  name: 'material'
  palette:
      primary: 'White'
      accent: 'Purple'
  font: 
    text: Roboto
    code: Roboto Mono
  logo: '/images/Logo.png'
  favicon: 'img/favicon.ico.png'

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML

markdown_extensions:
  - pymdownx.arithmatex
  