# Project information
site_name: 'My Notes' 
site_description: 'A Material Design theme for my personal notes'
site_author: 'Victor Andres Aguirre Fernandez'
site_url: ''

# Repository
repo_name: 'My_notes'
repo_url: 'https://github.com/CubeVic/My_notes'

# Copyright
copyright: 'Copyright &copy; 2019 -  Victor Aguirre'

theme:
  name: 'material'
  language: 'en'
  palette:
      primary: 'Deep Purple'
      accent: 'Deep Purple'
  font: 
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  logo: 'img/Logo.png'
  favicon: 'img/favicon.png'
  feature:
      tabs: true

use_directory_urls: false

extra_css:
  - stylesheets/dark_theme.css
  - stylesheets/codehilite.css
  - stylesheets/extra.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML

# Extensions
markdown_extensions:
  - pymdownx.arithmatex
  - admonition
  - footnotes
  - pymdownx.details
  - attr_list
  - smarty
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.tasklist:
      custom_checkbox: true
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
      separator: "_"


# Navigation
nav:
    - index.md
    - Machine Leaning:
      - Google Crash Course:
        - Problem Framing:  'Machine Learning/Google Crash Course/Problem_Framing.md'
        - ML Concepts: 
            - Framing: 'Machine Learning/Google Crash Course/ML Concepsts/Framing.md'
            - Linear Regression: 'Machine Learning/Google Crash Course/ML Concepsts/Linear regression.md'
            - Reducing Loss: 'Machine Learning/Google Crash Course/ML Concepsts/Reducing_Loss.md'
            - First Steps TensorFlow: 'Machine Learning/Google Crash Course/ML Concepsts/First_steps_TensorFlow.md'
            - Introduction to Pandas: 'Machine Learning/Google Crash Course/ML Concepsts/Intro_to_pandas.md'
            - Training and Test Sets: 'Machine Learning/Google Crash Course/ML Concepsts/Training_Test_sets.md'
      - Scripts and Projects:
        - Twitter Sentiment Analyzer: 'Machine Learning/Scripts or Projects/Twitter_sentiment_Analyzer.md'
      - Other Key Terminology (TensorFlow): 'Machine Learning/Other_key_Terminology.md'

    - Coding:
      - Python:
        - Preparation for PCPP-32-1:
          - Module 1: 'Coding/Python/Preparation for PCPP-32-1/Module 1.md'
          - Module 2: 'Coding/Python/Preparation for PCPP-32-1/Module 2.md'
        - Data Structures: 'Coding/Python/Data structures.md'
        - Control Flow: 'Coding/Python/control flow.md'
        - Functions: 'Coding/Python/functions.md'
        - Error and Exceptions: 'Coding/Python/Error and Exceptions.md'
        - Reading and Writing Files: 'Coding/Python/Reading and Writing Files.md'
        - Import Local Scripts: 'Coding/Python/Import Local Scripts.md'
        - Generator and Iterators: 'Coding/Python/Generator and Iterator.md'
        - Useful or researched built-in functions: 'Coding/Python/Useful or researched built-in functions.md'
        - Trick and tips for better code in python: 'Coding/Python/Tricks_tips_better_code_python.md'
        - Useful Snippets: 'Coding/Python/Useful_snippets.md'
        - Data bases with Python: 'Coding/Python/Databases_with_Python.md'
        - Virtual Environments: 'Coding/Python/virtual_environments.md'
        - Scripts:
          - Create Excel Files With Python: 'Coding/Python/Scripts/create_excel_files.md'
          - Creating a dataset with api and python: 'Coding/Python/Scripts/create_dataset_api_python.md'
          - Scraping Usign Python: 'Coding/Python/Scripts/Scraping_Usign_Python.md'
          - JSON Object in python: 'Coding/Python/Scripts/JSON Objects in Python.md'
          - Scrapy and Scrapyrt: 'Coding/Python/Scripts/Scrapy_and_Scrapyrt.md'
        - Algorithm:
          - Magic Square: 'Coding/Python/Algorithm/Magic_square.md'
        - Django:
          - Django Tutorial (part 01): 'Coding/Python/Django/Django tutorial - part 01.md'
          - Django Tutorial (part 02): 'Coding/Python/Django/Django tutorial - part 02.md'
          - Django Tutorial (part 03): 'Coding/Python/Django/Django tutorial - part 03.md'
          - (Optional) More details about file structure: 'Coding/Python/Django/More details about project structure.md'

      - SQL:
        - Random notes about SQL: 'Coding/SQL/Some_SQL.md'
        - String Funtions SQL: 'Coding/SQL/String_Functions_SQL.md'
        - Advance Funtion SQL: 'Coding/SQL/Advance_Funtion_SQL.md'

      - PowerLanguages:
        - PowerLanguages 001: 'Coding/PowerLanguages/PowerLanguages_001.md'
        - Reserved words: 'Coding/PowerLanguages/Reserved words.md'
        - How Scripts Work: 'Coding/PowerLanguages/how_script_works.md'
        - Functions: 'Coding/PowerLanguages/functions.md'
        - Plot: 'Coding/PowerLanguages/Plot.md'
        - Text and Trendlines: 'Coding/PowerLanguages/text_trendlines.md'

      - Arduino:
        - Structure: 
          - Sketch: 'Coding/Arduino/Structure/Sketch.md'
          - Control Structure: 'Coding/Arduino/Structure/Control_Structure.md'
          - Further Syntax: 'Coding/Arduino/Structure/Further_Syntax.md'
        - Variables:
          - Constants and Data Types: 'Coding/Arduino/Variables/Constants_and_Data_Types.md'
          - Conversion: 'Coding/Arduino/Variables/Conversion.md'
          - Variable Scope & Qualifiers: 'Coding/Arduino/Variables/Variable_Scope_Qualifiers.md'
        - Functions:
          - Digital I/O and Analog I/O: 'Coding/Arduino/Functions/Digital_and_Analog.md'
          - Time: 'Coding/Arduino/Functions/Time.md'
          - Math and Trigonometry: 'Coding/Arduino/Functions/Math_and_Trigonometry.md'
          - Characters: 'Coding/Arduino/Functions/Characters.md'
          - Random Numbers: 'Coding/Arduino/Functions/Random_Numbers.md'
          - Communication: 'Coding/Arduino/Functions/Communication.md'
          - Interrupts and External Interruptions: 'Coding/Arduino/Functions/Interrupts_and_External_Interruptions.md'
        - Projects:
          - Air Vent servo control: 'Coding/Arduino/Projects/Air_vent_servo_control.md'  

    - Courses:
          - Coursera:
            - AI for Everyone: 'Courses/Coursera/AI for Everyone/AI_for_Everyone.md'
            - Introduction tensorflow: 
              - The Hello World of neural networks: 'Courses/Coursera/Introduction tensorflow/The Hello World of neural networks.md'
              - Introduction to Computer vision: 'Courses/Coursera/Introduction tensorflow/Introduction to computer vision.md'
              - Convolutional Neural network Overview : 'Courses/Coursera/Introduction tensorflow/Convolutional_Neural_network_Overview.md'
              - Enhancing vision with convolutional Neural Networks : 'Courses/Coursera/Introduction tensorflow/Enhancing_vision_with_convolutional_Neural_Networks.md'
              - (Code) Step by step Convolutions : 'Courses/Coursera/Introduction tensorflow/Step_by_step_Convolutions.md'
              - Using Real-World Images: 'Courses/Coursera/Introduction tensorflow/Using_Real_world_Image.md'
          - Udemy:
            - Python Computer Vision and OpenCV:
              - Images Basic with OpenCV:
                - Numpy Basic (Part 1): 'Courses/Udemy/Python Computer Vision and OpenCV/Images Basic with OpenCV/Numpy_Basic_part_1.md'
                - Numpy Basic (Part 2): 'Courses/Udemy/Python Computer Vision and OpenCV/Images Basic with OpenCV/Numpy_Basic_part_2.md'
                - Images and Numpy: 'Courses/Udemy/Python Computer Vision and OpenCV/Images Basic with OpenCV/Images_and_Numpy.md'
                - Images and Opencv: 'Courses/Udemy/Python Computer Vision and OpenCV/Images Basic with OpenCV/Images_and_Opencv.md'
                - Drawing on Images: 'Courses/Udemy/Python Computer Vision and OpenCV/Images Basic with OpenCV/Drawing_on_Images.md'
                - Drawing with mouse: 'Courses/Udemy/Python Computer Vision and OpenCV/Images Basic with OpenCV/Direct_drawing_with_mouse.md'
              - Image Processing:
                - Color Mapping: 'Courses/Udemy/Python Computer Vision and OpenCV/Image Processing/color_mapping.md'
                - Blending and Pasting Images: 'Courses/Udemy/Python Computer Vision and OpenCV/Image Processing/blending_pasting_images.md'
            - Complete Tensorflow 2 and Keras Deep Learning Bootcamp:
                - Numpy Crash course: 'Courses/Udemy/Complete Tensorflow 2 and Keras Deep Learning Bootcamp/Numpy Crash course.md'
                - Pandas Crash course: 'Courses/Udemy/Complete Tensorflow 2 and Keras Deep Learning Bootcamp/Pandas Crash course.md'
                - Visualization Crash course: 'Courses/Udemy/Complete Tensorflow 2 and Keras Deep Learning Bootcamp/Visualization_Crash_course.md'
                - Artificial Neural Network: 'Courses/Udemy/Complete Tensorflow 2 and Keras Deep Learning Bootcamp/ANN.md'
          
    - 3D Printing:
      - Concepts: '3D Printing/Concepts.md'
      - G-code: '3D Printing/gcode.md'
      - Setup and Calibration:
          - Center and Z offset: '3D Printing/Setup and Calibration/Center and Z offset.md'
          - E-steps and Extrutor multiplier: '3D Printing/Setup and Calibration/E-steps and Extrutor multiplie.md'
          - Debuging and Logging: '3D Printing/Setup and Calibration/Debuging and Logging.md'
      - Projects: 
        - Moving Electronics: '3D Printing/Projects/Moving Electronics.md'
      - '3D Printing/about design.md'

    - Miscellaneous:
      - Aliases in Windows command prompt: 'Miscellaneous/Aliases_in_Windows_command_prompt.md'
      - Setting Open Media Vault: 'Miscellaneous/setting_openmediavault.md'
      - OAuth 2: 'Miscellaneous/OAuth_2.md'
      - Random: 'Miscellaneous/Random Link.md'
      #- Potential activities: 'Miscellaneous/potential activities.md'
      - How to Install OpenCv on Raspberry pi: 'Miscellaneous/How_install_openCV_raspberry.md'
    - About: 'about.md'
    - Helpers.md