# Project information
site_name: 'My Notes' 
site_description: 'A Material Design theme for my personal notes'
site_author: 'Victor Andres Aguirre Fernandez'
site_url: ''

# Repository
repo_name: 'My_notes'
repo_url: 'https://github.com/CubeVic/My_notes'

# Copyright
copyright: 'Copyright &copy; 2019 -  Victor Aguirre'

theme:
  name: 'material'
  language: 'en'
  palette:
      primary: 'Deep Purple'
      accent: 'Deep Purple'
  font: 
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  logo: 'img/Logo.png'
  favicon: 'img/favicon.png'
  feature:
      tabs: true

use_directory_urls: false

extra_css:
  - stylesheets/dark_theme.css
  - stylesheets/codehilite.css
  - stylesheets/extra.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML

# Extensions
markdown_extensions:
  - pymdownx.arithmatex
  - admonition
  - footnotes
  - pymdownx.details
  - attr_list
  - smarty
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.tasklist:
      custom_checkbox: true
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
      separator: "_"


# Navigation
nav:
    - index.md
    - Machine Leaning:
      - Google Crash Course:
        - Problem Framing:  'Machine Learning/Google Crash Course/Problem_Framing.md'
        - ML Concepts: 
            - Framing: 'Machine Learning/Google Crash Course/ML Concepsts/Framing.md'
            - Linear Regression: 'Machine Learning/Google Crash Course/ML Concepsts/Linear regression.md'
            - Reducing Loss: 'Machine Learning/Google Crash Course/ML Concepsts/Reducing_Loss.md'
            - First Steps TensorFlow: 'Machine Learning/Google Crash Course/ML Concepsts/First_steps_TensorFlow.md'
            - Introduction to Pandas: 'Machine Learning/Google Crash Course/ML Concepsts/Intro_to_pandas.md'
            - Training and Test Sets: 'Machine Learning/Google Crash Course/ML Concepsts/Training_Test_sets.md'
      - Scripts and Projects:
        - Twitter Sentiment Analyzer: 'Machine Learning/Scripts or Projects/Twitter_sentiment_Analyzer.md'
      - Other Key Terminology (TensorFlow): 'Machine Learning/Other_key_Terminology.md'

    - Python:
      - Preparation for PCPP-32-1:
          - Module 1: 'Python/Preparation for PCPP-32-1/Module 1.md'
      - Data Structures: 'Python/Data structures.md'
      - Control Flow: 'Python/control flow.md'
      - Functions: 'Python/functions.md'
      - Error and Exceptions: 'Python/Error and Exceptions.md'
      - Reading and Writing Files: 'Python/Reading and Writing Files.md'
      - Import Local Scripts: 'Python/Import Local Scripts.md'
      - Generator and Iterators: 'Python/Generator and Iterator.md'
      - Useful or researched built-in functions: 'Python/Useful or researched built-in functions.md'
      - Trick and tips for better code in python: 'Python/Tricks_tips_better_code_python.md'
      - Useful Snippets: 'Python/Useful_snippets.md'
      - Data bases with Python: 'Python/Databases_with_Python.md'
      - Virtual Environments: 'Python/virtual_environments.md'
      - Scripts:
          - Create Excel Files With Python: 'Python/Scripts/create_excel_files.md'
          - Creating a dataset wth api and python: 'Python/Scripts/create_dataset_api_python.md'
          - Scraping Usign Python: 'Python/Scripts/Scraping_Usign_Python.md'
      - Algorithm:
          - Magic Square: 'Python/Algorithm/Magic_square.md'
      - Django:
        - Django Tutorial (part 01): 'Python/Django/Django tutorial - part 01.md'
        - Django Tutorial (part 02): 'Python/Django/Django tutorial - part 02.md'
        - (Optional) More details about file structure: 'Python/Django/More details about project structure.md'

    - SQL:
      - Random notes about SQL: 'SQL/Some_SQL.md'
      - String Funtions SQL: 'SQL/String_Functions_SQL.md'
      - Advance Funtion SQL: 'SQL/Advance_Funtion_SQL.md'

    - Courses:
          - Coursera:
            - AI for Everyone: 'Courses/Coursera/AI for Everyone/AI_for_Everyone.md'
            - Introduction tensorflow: 
              - The Hello World of neural networks: 'Courses/Coursera/Introduction tensorflow/The Hello World of neural networks.md'
              - Introduction to Computer vision: 'Courses/Coursera/Introduction tensorflow/Introduction to computer vision.md'
              - Convolutional Neural network Overview : 'Courses/Coursera/Introduction tensorflow/Convolutional_Neural_network_Overview.md'
              - Enhancing vision with convolutional Neural Networks : 'Courses/Coursera/Introduction tensorflow/Enhancing_vision_with_convolutional_Neural_Networks.md'
              - (Code) Step by step Convolutions : 'Courses/Coursera/Introduction tensorflow/Step_by_step_Convolutions.md'
              - Using Real-World Images: 'Courses/Coursera/Introduction tensorflow/Using_Real_world_Image.md'
          - Udemy:
            - Python Computer Vision and OpenCV:
              - Images Basic with OpenCV:
                - Numpy Basic (Part 1): 'Courses/Udemy/Python Computer Vision and OpenCV/Images Basic with OpenCV/Numpy_Basic_part_1.md'
                - Numpy Basic (Part 2): 'Courses/Udemy/Python Computer Vision and OpenCV/Images Basic with OpenCV/Numpy_Basic_part_2.md'
                - Images and Numpy: 'Courses/Udemy/Python Computer Vision and OpenCV/Images Basic with OpenCV/Images_and_Numpy.md'
                - Images and Opencv: 'Courses/Udemy/Python Computer Vision and OpenCV/Images Basic with OpenCV/Images_and_Opencv.md'
                - Drawing on Images: 'Courses/Udemy/Python Computer Vision and OpenCV/Images Basic with OpenCV/Drawing_on_Images.md'
                - Drawing with mouse: 'Courses/Udemy/Python Computer Vision and OpenCV/Images Basic with OpenCV/Direct_drawing_with_mouse.md'
              - Image Processing:
                - Color Mapping: 'Courses/Udemy/Python Computer Vision and OpenCV/Image Processing/color_mapping.md'
                - Blending and Pasting Images: 'Courses/Udemy/Python Computer Vision and OpenCV/Image Processing/blending_pasting_images.md'

    - PowerLanguages:
      - PowerLanguages 001: 'PowerLanguages/PowerLanguages_001.md'
      - Reserved words: 'PowerLanguages/Reserved words.md'
      - How Scripts Work: 'PowerLanguages/how_script_works.md'
      - Functions: 'PowerLanguages/functions.md'
      - Plot: 'PowerLanguages/Plot.md'
      - Text and Trendlines: 'PowerLanguages/text_trendlines.md'

    - Arduino:
      - Structure: 
        - Sketch: 'Arduino/Structure/Sketch.md'
        - Control Structure: 'Arduino/Structure/Control_Structure.md'
        - Further Syntax: 'Arduino/Structure/Further_Syntax.md'
      - Variables:
        - Constants and Data Types: 'Arduino/Variables/Constants_and_Data_Types.md'
        - Conversion: 'Arduino/Variables/Conversion.md'
        - Variable Scope & Qualifiers: 'Arduino/Variables/Variable_Scope_Qualifiers.md'
      - Functions:
        - Digital I/O and Analog I/O: 'Arduino/Functions/Digital_and_Analog.md'
        - Time: 'Arduino/Functions/Time.md'
        - Math and Trigonometry: 'Arduino/Functions/Math_and_Trigonometry.md'
        - Characters: 'Arduino/Functions/Characters.md'
        - Random Numbers: 'Arduino/Functions/Random_Numbers.md'
        - Communication: 'Arduino/Functions/Communication.md'
        - Interrupts and External Interruptions: 'Arduino/Functions/Interrupts_and_External_Interruptions.md'
      - Projects:
        - Ikea Lack Table - Enclosure:
          - Air Vent servo control: Arduino/Projects/Ikea Lack Table - Enclosure/Air_vent_servo_control.md        
    
    - 3D Printing:
      - Setup and Calibration:
          - Center and Z offset: '3D Printing/Setup and Calibration/Center and Z offset.md'
          - E-steps and Extrutor multiplier: '3D Printing/Setup and Calibration/E-steps and Extrutor multiplie.md'
          - Debuging and Logging: '3D Printing/Setup and Calibration/Debuging and Logging.md'
      - Projects: 
        - Moving Electronics: '3D Printing/Projects/Moving Electronics.md'
      - '3D Printing/about design.md'

    - Miscellaneous:
      - Aliases in Windows command prompt: 'Miscellaneous/Aliases_in_Windows_command_prompt.md'
      - Setting Open Media Vault: 'Miscellaneous/setting_openmediavault.md'
      - OAuth 2: 'Miscellaneous/OAuth_2.md'
      - Random: 'Miscellaneous/Random Link.md'
      #- Potential activities: 'Miscellaneous/potential activities.md'
      - How to Install OpenCv on Raspberry pi: 'Miscellaneous/How_install_openCV_raspberry.md'
    - About: 'about.md'
    - Helpers.md