# Project information
site_name: 'My Notes' 
site_description: 'A Material Design theme for my personal notes'
site_author: 'Victor Andres Aguirre Fernandez'
site_url: ''

# Repository
repo_name: 'My_notes'
repo_url: 'https://github.com/CubeVic/My_notes'

# Copyright
copyright: 'Copyright &copy; 2019 -  Victor Aguirre'

theme:
  name: 'material'
  language: 'en'
  palette:
      primary: 'grey'
      accent: 'Indigo'
  font: 
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  logo: '/images/Logo.png'
  favicon: 'img/favicon.ico.png'
  feature:
      tabs: true

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML

# Extensions
markdown_extensions:
  - pymdownx.arithmatex
  - admonition
  - footnotes
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
      separator: "_"


# Navigation
nav:
    - Home: 'index.md'
    - Machine Leaning: 
      - Key ML Terminology: 'Machine Learning/Key ML Terminology.md'
      - Other Key Terminology (TensorFlow): 'Machine Learning/Other_key_Terminology.md'
      - Linear Regression: 'Machine Learning/Linear regression.md'
    - Python:
      - Data Structures: 'Python/Data structures.md'
      - Control Flow: 'Python/control flow.md'
      - Functions: 'Python/functions.md'
      - Error and Exceptions: 'Python/Error and Exceptions.md'
      - Reading and Writing Files: 'Python/Reading and Writing Files.md'
      - Import Local Scripts: 'Python/Import Local Scripts.md'
      - Generator and Iterators: 'Python/Generator and Iterator.md'
      - Useful or researched built-in functions: 'Python/Useful or researched built-in functions.md'
    - Django:
      - Django Tutorial (part 01): 'Django/Django tutorial - part 01.md'
      - (Optional) More details about file structure: 'Django/More details about project structure.md'
    - SQL:
      - Miscellaneous: 'SQL/Miscellaneous.md'
    - Miscellaneous:
      - OAuth 2: 'Miscellaneous/OAuth_2.md'
      - Random: 'Miscellaneous/Random Link.md'
      - Potential activities: 'Miscellaneous/potential activities.md'
    - Courses:
          - Coursera:
            - AI for Everyone: 'Courses/Coursera/AI for Everyone/AI_for_Everyone.md'
    - About: 'about.md'