# Project information
site_name: 'My Notes' 
site_description: 'A Material Design theme for my personal notes'
site_author: 'Victor Andres Aguirre Fernandez'
site_url: ''

# Repository
repo_name: 'My_notes'
repo_url: 'https://github.com/CubeVic/My_notes'

# Copyright
copyright: 'Copyright &copy; 2019 -  Victor Aguirre'

theme:
  name: 'material'
  language: 'en'
  palette:
      primary: 'Indigo'
      accent: 'Grey'
  font: 
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  logo: '/images/Logo.png'
  favicon: 'img/favicon.ico.png'
  feature:
      tabs: true

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML

# Extensions
markdown_extensions:
  - pymdownx.arithmatex
  - admonition
  - footnotes
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
      separator: "_"


# Navigation
nav:
    - Home: 'index.md'
    - Machine Leaning:
      - Google Crash Course:
        - Problem Framing:  'Machine Learning/Google Crash Course/Problem_Framing.md'
      - Key ML Terminology: 'Machine Learning/Key ML Terminology.md'
      - Linear Regression: 'Machine Learning/Linear regression.md'
      - Other Key Terminology (TensorFlow): 'Machine Learning/Other_key_Terminology.md'
    - Python:
      - Data Structures: 'Python/Data structures.md'
      - Control Flow: 'Python/control flow.md'
      - Functions: 'Python/functions.md'
      - Error and Exceptions: 'Python/Error and Exceptions.md'
      - Reading and Writing Files: 'Python/Reading and Writing Files.md'
      - Import Local Scripts: 'Python/Import Local Scripts.md'
      - Generator and Iterators: 'Python/Generator and Iterator.md'
      - Useful or researched built-in functions: 'Python/Useful or researched built-in functions.md'
      - Trick and tips for better code in python: 'Python/Tricks_tips_better_code_python.md'
      - Algorithm:
          - Magic Square: 'Python/Algorithm/Magic_square.md'
    - Django:
      - Django Tutorial (part 01): 'Django/Django tutorial - part 01.md'
      - Django Tutorial (part 02): 'Django/Django tutorial - part 02.md'
      - (Optional) More details about file structure: 'Django/More details about project structure.md'
    - SQL:
      - Random notes about SQL: 'SQL/Some_SQL.md'
      - String Funtions SQL: 'SQL/String_Functions_SQL.md'
      - Advance Funtion SQL: 'SQL/Advance_Funtion_SQL.md'
    - Courses:
          - Coursera:
            - AI for Everyone: 'Courses/Coursera/AI for Everyone/AI_for_Everyone.md'
            - Introduction tensorflow: 
              - The Hello World of neural networks: 'Courses/Coursera/Introduction tensorflow/The Hello World of neural networks.md'
              - Introduction to Computer vision: 'Courses/Coursera/Introduction tensorflow/Introduction to computer vision.md'
              - Convolutional Neural network Overview : 'Courses/Coursera/Introduction tensorflow/Convolutional_Neural_network_Overview.md'
              - Enhancing vision with convolutional Neural Networks : 'Courses/Coursera/Introduction tensorflow/Enhancing_vision_with_convolutional_Neural_Networks.md'
              - (Code) Step by step Convolutions : 'Courses/Coursera/Introduction tensorflow/Step_by_step_Convolutions.md'
              - Using Real-World Images: 'Courses/Coursera/Introduction tensorflow/Using_Real_world_Image.md'
          - Udemy:
            - Python Computer Vision and OpenCV:
              - Numpy Basic (Part 1): 'Courses/Udemy/Python Computer Vision and OpenCV/Numpy_Basic_part_1.md'
              - Numpy Basic (Part 2): 'Courses/Udemy/Python Computer Vision and OpenCV/Numpy_Basic_part_2.md'
              - Images and Numpy: 'Courses/Udemy/Python Computer Vision and OpenCV/Images_and Numpy.md'
    - Miscellaneous:
      - Aliases in Windows command prompt: 'Miscellaneous/Aliases_in_Windows_command_prompt.md'
      - OAuth 2: 'Miscellaneous/OAuth_2.md'
      - Random: 'Miscellaneous/Random Link.md'
      - Potential activities: 'Miscellaneous/potential activities.md'
    - About: 'about.md'