# Project information
site_name: 'My Notes' 
site_description: 'A Material Design theme for my personal notes'
site_author: 'Victor Andres Aguirre Fernandez'
site_url: 'https://cubevic.github.io/My_notes/'

# Repository
repo_name: 'My_notes'
repo_url: 'https://github.com/CubeVic/My_notes'

# Copyright
copyright: 'Copyright &copy; 2019 -  Victor Aguirre'

theme:
  name: 'material'
  language: 'en'
  palette:
      primary: 'Deep purple'
      accent: 'Deep purple'
  font: 
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  logo: 'img/Logo.svg'
  favicon: 'img/favicon.png'
  features:
    - navigation.tabs

use_directory_urls: false

extra_css:
  - stylesheets/dark_theme.css
  - stylesheets/codehilite.css
  - stylesheets/extra.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-MML-AM_CHTML

# Extensions
markdown_extensions:
  - pymdownx.arithmatex
  - admonition
  - footnotes
  - pymdownx.details
  - attr_list
  - smarty
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.tasklist:
      custom_checkbox: true
  - codehilite:
      guess_lang: false
      linenums: true
  - toc:
      permalink: true
      separator: "_"


# Navigation
nav:
    # - Home: index.md
    - Machine Leaning (Concepts):
      - Google Crash Course:
        - Problem Framing:  'Machine Learning/Google Crash Course/Problem_Framing.md'
        - ML Concepts: 
            - Framing: 'Machine Learning/Google Crash Course/ML Concepts/Framing.md'
            - Linear Regression: 'Machine Learning/Google Crash Course/ML Concepts/Linear regression.md'
            - Reducing Loss: 'Machine Learning/Google Crash Course/ML Concepts/Reducing_Loss.md'
            - First Steps TensorFlow: 'Machine Learning/Google Crash Course/ML Concepts/First_steps_TensorFlow.md'
            - Introduction to Pandas: 'Machine Learning/Google Crash Course/ML Concepts/Intro_to_pandas.md'
            - Training and Test Sets: 'Machine Learning/Google Crash Course/ML Concepts/Training_Test_sets.md'
      - AI for Everyone: 'Machine Learning/AI for Everyone/AI_for_Everyone.md'
      - Other Key Terminology (TensorFlow): 'Machine Learning/Other_key_Terminology.md'
      - ML script or projects:
        - Twitter Sentiment Analyzer: 'Machine Learning/ML script or projects/Twitter_sentiment_Analyzer.md' 
    
    - Python:
      - Introduction: 'Python/introduction.md'
      - Python Basics:  
        - Data Structures: 'Python/Python_Basics/Data structures.md'
        - Control Flow: 'Python/Python_Basics/control flow.md'
        - Functions: 'Python/Python_Basics/functions.md'
        - Error and Exceptions: 'Python/Python_Basics/Error and Exceptions.md'
        - Reading and Writing Files: 'Python/Python_Basics/Reading and Writing Files.md'
        - Import Local Scripts: 'Python/Python_Basics/Import Local Scripts.md'
        - Generator and Iterators: 'Python/Python_Basics/Generator and Iterator.md'
        - Useful or researched built-in functions: 'Python/Python_Basics/Useful or researched built-in functions.md'
        - Data bases with Python: 'Python/Python_Basics/Databases_with_Python.md'
        - Useful Snippets: 'Python/Python_Basics/Useful_snippets.md'
        - Trick and tips for better code in python: 'Python/Python_Basics/Tricks_tips_better_code_python.md'
      - Python intermediate: 
        - Context Managers 'with': 'Python/Python_intermediate/context_manager_python.md'
        - Multi-threading and Multi-processing: 'Python/Python_intermediate/Multithreading_and_multiprocessing.md'      
        - SQLAchemy: 'Python/Python_intermediate/sqlalchemy.md'
      - Libraries & Modules: #Libraries and Modules
        - PIP notes: 'Python/Libraries_and_Modules/PIP/pip_notes.md'
        - Itertools:
            - Introductions: 'Python/Libraries_and_Modules/Itertools/introduction.md'
            - Infinite iterators:
              - count(): 'Python/Libraries_and_Modules/Itertools/Infinite_iterators/count.md'
              - cycle(): 'Python/Libraries_and_Modules/Itertools/Infinite_iterators/cycle.md'
              - repeat(): 'Python/Libraries_and_Modules/Itertools/Infinite_iterators/repeat.md'
            - Combinatoric iterator:
              - permutations(): 'Python/Libraries_and_Modules/Itertools/Combinatoric_iterator/permutations.md'
              - combinations(): 'Python/Libraries_and_Modules/Itertools/Combinatoric_iterator/combinations.md'
            - Shortest input equence:
                - groupby(): 'Python/Libraries_and_Modules/Itertools/Combinatoric_iterator/Shortest_input_sequence/groupby.md'
        - Numpy:
          - Numpy Basic (Part 1): 'Python/Libraries_and_Modules/Numpy/Numpy_Basic_part_1.md'
          - Numpy Basic (Part 2): 'Python/Libraries_and_Modules/Numpy/Numpy_Basic_part_2.md'
          - Numpy Crash course: 'Python/Libraries_and_Modules/Numpy/Numpy Crash course.md'
        - Pandas (Under Review):
          - Pandas Crash course: 'Python/Libraries_and_Modules/Pandas/Pandas Crash course.md'
        - OpenCV:
          - Images Basic with OpenCV:
            - Images and Numpy: 'Python/Libraries_and_Modules/Computer Vision and OpenCV/Images Basic with OpenCV/Images_and_Numpy.md'
            - Images and Opencv: 'Python/Libraries_and_Modules/Computer Vision and OpenCV/Images Basic with OpenCV/Images_and_Opencv.md'
            - Drawing on Images: 'Python/Libraries_and_Modules/Computer Vision and OpenCV/Images Basic with OpenCV/Drawing_on_Images.md'
            - Drawing with mouse: 'Python/Libraries_and_Modules/Computer Vision and OpenCV/Images Basic with OpenCV/Direct_drawing_with_mouse.md'
          - Image Processing:
            - Color Mapping: 'Python/Libraries_and_Modules/Computer Vision and OpenCV/Image Processing/color_mapping.md'
            - Blending and Pasting Images: 'Python/Libraries_and_Modules/Computer Vision and OpenCV/Image Processing/blending_pasting_images.md'
        - Netifaces:
          - Introduction: 'Python/Libraries_and_Modules/netifaces/introduction.md'
        - WS Discovery:
          - Introduction: 'Python/Libraries_and_Modules/WS_Discovery/introduction.md'
        - ONVIF-zeep-async:
          - Introduction: 'Python/Libraries_and_Modules/ONVIF_python_zeep_async/introduction.md'
        - Pillow:
          - Introduction: 'Python/Libraries_and_Modules/Pillow/introduction.md'
        - QR Code:
          - Introduction: 'Python/Libraries_and_Modules/QRcode/introduction.md'
        - HTTPX:
          - Introduction: 'Python/Libraries_and_Modules/HTTPX/introduction.md'
        - Datamuse: 
          - Introduction: 'Python/Libraries_and_Modules/Datamuse/introduction.md'
        - Crontab:
          - Introduction: 'Python/Libraries_and_Modules/Crontab/introduction.md'
      - Frameworks: 
        - Flask:
          - Introduction and notes: 'Python/Frameworks/Flask/Introduction_and_notes.md'
          - Quick & Dirty First App: 'Python/Frameworks/Flask/first_app_flask.md'
          - Tutorial From Official Documentation:
            - Application Layout (Structure): 'Python/Frameworks/Flask/from_Official_documentation/flask_structure.md'
            - Application Factory & Run: 'Python/Frameworks/Flask/from_Official_documentation/flask_application_factory.md'
            - Application Database: 'Python/Frameworks/Flask/from_Official_documentation/flask_database.md'
            - Blueprints (part 01-Auth): 'Python/Frameworks/Flask/from_Official_documentation/flask_blueprints_part1.md'
            - Templates: 'Python/Frameworks/Flask/from_Official_documentation/flask_templates.md'
            - Blueprints (part 02-Blog): 'Python/Frameworks/Flask/from_Official_documentation/flask_blueprints_part2.md'
          - Flask Extensions:
              - Forms - Flask-WTF: 'Python/Frameworks/Flask/Extensions/forms_flask_wtf.md'
              - Databases - Flask-SQLAlchemy: 'Python/Frameworks/Flask/Extensions/database_flask_sqlalchemy.md'
              - Databases(Migration) - Flask-Migration: "Python/Frameworks/Flask/Extensions/database_migration_flask_migration.md"
              - Login - Flask-login: "Python/Frameworks/Flask/Extensions/login_flask_login.md"
 #       - Django:
 #         - Django Tutorial (part 01): 'Python/Frameworks/Django/Django tutorial - part 01.md'
 #         - Django Tutorial (part 02): 'Python/Frameworks/Django/Django tutorial - part 02.md'
 #         - Django Tutorial (part 03): 'Python/Frameworks/Django/Django tutorial - part 03.md'
 #         - (Optional) More details about file structure: 'Python/Frameworks/Django/More details about project structure.md'
        - Scrapy:
          - Introduction: 'Python/Frameworks/Scrapy/introduction.md'
          - Splash: 'Python/Frameworks/Scrapy/splash.md'
          - Running_multiple_spider: 'Python/Frameworks/Scrapy/Running_multiple_spider.md'
      - Projects:
        - Random Password Generator: 'Python/Projects/random_password_generator.md'
      - Scripts & Algorithms:
        - Create Excel Files With Python: 'Python/Scripts/create_excel_files.md'
        - Creating a dataset with api and python: 'Python/Scripts/create_dataset_api_python.md'
        - Scraping Usign Python: 'Python/Scripts/Scraping_Usign_Python.md'
        - JSON Object in python: 'Python/Scripts/JSON Objects in Python.md'
        - Scrapy and Scrapyrt: 'Python/Scripts/Scrapy_and_Scrapyrt.md'
        - Magic Square: 'Python/Scripts/Magic_square.md'
      - Virtual Environments: 'Python/virtual_environments.md'
         
    - SQL:
      - Random notes about SQL: 'SQL/Some_SQL.md'
      - String Funtions SQL: 'SQL/String_Functions_SQL.md'
      - Advance Funtion SQL: 'SQL/Advance_Funtion_SQL.md'

    - Arduino:
      - Structure: 
        - Sketch: 'Arduino/Structure/Sketch.md'
        - Control Structure: 'Arduino/Structure/Control_Structure.md'
        - Further Syntax: 'Arduino/Structure/Further_Syntax.md'
      - Variables:
        - Constants and Data Types: 'Arduino/Variables/Constants_and_Data_Types.md'
        - Conversion: 'Arduino/Variables/Conversion.md'
        - Variable Scope & Qualifiers: 'Arduino/Variables/Variable_Scope_Qualifiers.md'
      - Functions:
        - Digital I/O and Analog I/O: 'Arduino/Functions/Digital_and_Analog.md'
        - Time: 'Arduino/Functions/Time.md'
        - Math and Trigonometry: 'Arduino/Functions/Math_and_Trigonometry.md'
        - Characters: 'Arduino/Functions/Characters.md'
        - Random Numbers: 'Arduino/Functions/Random_Numbers.md'
        - Communication: 'Arduino/Functions/Communication.md'
        - Interrupts and External Interruptions: 'Arduino/Functions/Interrupts_and_External_Interruptions.md'
      - Projects:
        - Morse code Translator: 'Arduino/Projects/Morse_code_Translator.md'
        - Air Vent servo control: 'Arduino/Projects/Air_vent_servo_control.md'  

    - APIs:
      - datamuse: 'APIs/datamuse.md'
      - Google API:
        - introduction: 'APIs/Google/introduction.md'
        - sheets:
          - Google Sheet API: 'APIs/Google/sheets/google_sheet_api.md'
          - Create spreadsheets: 'APIs/Google/sheets/google_sheet_create.md'
          - Read and Write spreadsheets: 'APIs/Google/sheets/google_sheet_read.md'
          - Update spreadsheets: 'APIs/Google/sheets/google_sheet_update.md'

    - Raspberry:
      - Samba Server: 'Raspberry/samba.md'
      - Nagios Core: 'Raspberry/Nagios.md'
      - How to Install OpenCv on Raspberry pi: 'Raspberry/How_install_openCV_raspberry.md'
      - Raspberry Password Related: 'Raspberry/Password_related_raspberry.md' 
      - Setting Open Media Vault: 'Raspberry/setting_openmediavault.md'   

    - CCTV:
      - Basic Concepts: 'CCTV/Basic_concepts.md'
      - Lens mount: 'CCTV/lens_mount.md'
      - SoC: 'CCTV/SoC.md'
      - STARVIS sensor: 'CCTV/starvis.md'
      - ACTi URL commands: 
        - URL Commands Basics: 'CCTV/ACTi/ACTi_URL_Commands.md'
      - Wireshark: 'CCTV/wireshark.md'
      - Windows errors: 'CCTV/windows_error.md'
      - what is hypercoverged infrastructure: 'CCTV/hypercoverged_infrastructure.md'

    - Miscellaneous:
      - Helpers: 'Miscellaneous/Helpers.md'
      - Espanso ( shortcuts ): 'Miscellaneous/Espanso.md'
      - PowerLanguages:
        - Reference: 'Miscellaneous/PowerLanguages/PowerLanguages_001.md'
        - Reserved words: 'Miscellaneous/PowerLanguages/Reserved words.md'
        - How Scripts Work: 'Miscellaneous/PowerLanguages/how_script_works.md'
        - Functions: 'Miscellaneous/PowerLanguages/functions.md'
        - Plot: 'Miscellaneous/PowerLanguages/Plot.md'
        - Text and Trendlines: 'Miscellaneous/PowerLanguages/text_trendlines.md'
      - 3D Printing:
        - Concepts: 'Miscellaneous/3D Printing/Concepts.md'
        - G-code: 'Miscellaneous/3D Printing/gcode.md'
        - Setup and Calibration:
            - Center and Z offset: 'Miscellaneous/3D Printing/Setup and Calibration/Center and Z offset.md'
            - E-steps and Extrutor multiplier: 'Miscellaneous/3D Printing/Setup and Calibration/E-steps and Extrutor multiplie.md'
            - Debuging and Logging: 'Miscellaneous/3D Printing/Setup and Calibration/Debuging and Logging.md'
        - Projects:
          - Moving Electronics: 'Miscellaneous/3D Printing/Projects/Moving Electronics.md'
        - About design: 'Miscellaneous/3D Printing/about design.md'
      - Courses:
        - Coursera:
          - Introduction tensorflow: 
            - The Hello World of neural networks: 'Miscellaneous/Courses/Coursera/Introduction tensorflow/The Hello World of neural networks.md'
            - Introduction to Computer vision: 'Miscellaneous/Courses/Coursera/Introduction tensorflow/Introduction to computer vision.md'
            - Convolutional Neural network Overview : 'Miscellaneous/Courses/Coursera/Introduction tensorflow/Convolutional_Neural_network_Overview.md'
            - Enhancing vision with convolutional Neural Networks : 'Miscellaneous/Courses/Coursera/Introduction tensorflow/Enhancing_vision_with_convolutional_Neural_Networks.md'
            - (Code) Step by step Convolutions : 'Miscellaneous/Courses/Coursera/Introduction tensorflow/Step_by_step_Convolutions.md'
            - Using Real-World Images: 'Miscellaneous/Courses/Coursera/Introduction tensorflow/Using_Real_world_Image.md'
          - Convolutional Neural Networks in TensorFlow: 
            - Exploring large Datasets - Cats vs Dogs : 'Miscellaneous/Courses/Coursera/Convolutional Neural Networks in TensorFlow/exploring_large_dataset.md'
            - Augmentation: 'Miscellaneous/Courses/Coursera/Convolutional Neural Networks in TensorFlow/Augmentation_technique_to_avoid_overfitting.md'
            - Transfer Learning: 'Miscellaneous/Courses/Coursera/Convolutional Neural Networks in TensorFlow/Transfer_Learning.md'
        - Udemy:
          - Complete Tensorflow 2 and Keras Deep Learning Bootcamp:        
            - Visualization Crash course: 'Miscellaneous/Courses/Udemy/Complete Tensorflow 2 and Keras Deep Learning Bootcamp/Visualization_Crash_course.md'
            - Artificial Neural Network: 'Miscellaneous/Courses/Udemy/Complete Tensorflow 2 and Keras Deep Learning Bootcamp/ANN.md'
      - For Certifications:
        - Python(PCPP-32-1):
          - Module 1: 'Miscellaneous/For Certifications/Python/Preparation for PCPP-32-1/Module 1.md'
          - Module 2: 'Miscellaneous/For Certifications/Python/Preparation for PCPP-32-1/Module 2.md'
      - Aliases in Windows command prompt: 'Miscellaneous/Aliases_in_Windows_command_prompt.md'
      - OAuth 2: 'Miscellaneous/OAuth_2.md'
      - Random: 'Miscellaneous/Random Link.md'
      #- Potential activities: 'Miscellaneous/potential activities.md'
      - Configuration for Sublime Text 3: 'Miscellaneous/Sublime_text.md'
    - About: 'about.md'